name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn run lint

    - name: Build
      run: yarn run build

    - name: Test
      run: yarn run test

    - name: Package
      run: yarn run package

    - name: Deploy
      if: github.ref == 'refs/heads/master' && github.repository == 'blacha/st'
      run: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

